version: 0.0
os: linux
files:
  - source: .
    destination: /app
hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
    - location: scripts/install_aws_cli.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/pull_envs.sh
    - location: scripts/empty_deployments_bucket.sh
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
