services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    env_file:
      - apps/client/.env
    ports:
      - "3000:3000"
