version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - ./client/.env
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"
