name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      BE_IMAGE_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.BE_DOCKER_IMAGE_NAME }}:latest
      BE_PATH: ./apps/backend/
      FE_IMAGE_TAG: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ vars.FE_DOCKER_IMAGE_NAME }}:latest
      FE_PATH: ./apps/client/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SA }}"
      - name: Set up BE Env
        run: |
          echo "${{ secrets.ENV_BE }}" >> ${{ env.BE_PATH }}/.env
      - name: Set up FE Env
        run: |
          echo "${{ secrets.ENV_FE }}" >> ${{ env.FE_PATH }}/.env
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push BE
        id: docker_build_be
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.BE_PATH }}/Dockerfile
          push: true
          tags: ${{ env.BE_IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push FE
        id: docker_build_fe
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.FE_PATH }}/Dockerfile
          push: true
          tags: ${{ env.FE_IMAGE_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Deploy BE to Cloud Run
        run: |
          gcloud run deploy ${{ vars.BE_CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ env.BE_IMAGE_TAG }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --async
      - name: Deploy FE to Cloud Run
        run: |
          gcloud run deploy ${{ vars.FE_CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ env.FE_IMAGE_TAG }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --async
